# Chance is 1-50, 50 = always, 1 = very rare
rewards:
  DiamondReward:
    chance: 5
    items:
      - "minecraft:diamond:1"
    commands:
      - "give {PLAYER} diamond 40"
  KeyReward:
    chance: 15
    items: []
    commands:
      - "keyall"
  GoldReward:
    chance: 20
    items:
      - "minecraft:gold_ingot:10"
    commands: []
