# Chance is 1-50, 50 = always, 1 = very rare
rewards:
  Uncommon:
    chance: 10
    items:
      - "diamond_ore"
      - "gold_block"
    commands:
      - "give {PLAYER} diamond_ore 40"
  Common:
    chance: 8
    items:
      - "diamond_ore"
      - "gold_block"
    commands:
      - "give {PLAYER} diamond_ore 40"
  Epic:
    chance: 5
    items:
      - "diamond_ore"
      - "gold_block"
    commands:
      - "give {PLAYER} diamond_ore 40"
  Legendary:
    chance: 2
    items:
      - "diamond_ore"
      - "gold_block"
    commands:
      - "give {PLAYER} diamond_ore 40"
